services:
  - type: web
    name: finance-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: API_TOKEN
        sync: false 