services:
  - type: background
    name: finance-bot
    env: python
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: API_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
    autoDeploy: true
